@startuml C4_Context_Deposit_MVP
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()

title Диаграмма Контекста: MVP Онлайн-подача заявок на депозит

Person(new_client, "Новый Клиент", "Потенциальный клиент банка")
Person(existing_client, "Существующий Клиент", "Клиент банка")
Person(back_office_emp, "Сотрудник Бэк-офиса", "Обрабатывает заявки, управляет ставками")
Person(cc_operator, "Оператор Колл-центра", "Консультирует клиентов")

System(website, "Веб-сайт Банка", "Публичный сайт с информацией и формой заявки")
System(ib, "Интернет-Банк", "Система для существующих клиентов")
System(abs, "АБС", "Автоматизированная Банковская Система. Ядро банка")
System(cc_system, "Система Колл-центра", "Платформа для обработки звонков и обращений")
System(sms_gateway, "СМС-шлюз", "Внешний сервис для отправки СМС")

System_Ext(partner_cc_system, "Система Партнерского КЦ", "Внешняя система")

Rel(new_client, website, "Подает заявку на депозит, просматривает ставки")
Rel(existing_client, ib, "Подает заявку на депозит, просматривает ставки, подтверждает СМС")

Rel(website, cc_system, "Передает заявку нового клиента", "HTTPS/API")
Rel(cc_operator, cc_system, "Обрабатывает заявку с сайта")
Rel(cc_system, abs, "Передает данные по заявке (возможно, частично вручную на MVP)", "API/File")

Rel(ib, sms_gateway, "Отправляет СМС-код для подтверждения операции", "API")
Rel(ib, abs, "Передает заявку на депозит (асинхронно через Kafka)", "Kafka")
Rel(website, abs, "Получает актуальные ставки (через Сервис Ставок в АБС)", "API")
Rel(ib, abs, "Получает актуальные/персональные ставки (через Сервис Ставок в АБС)", "API")


Rel(back_office_emp, abs, "Обрабатывает заявки, управляет ставками")
Rel(abs, sms_gateway, "Отправляет СМС-уведомления о статусе заявки/депозита", "API")

@enduml